### ISSUE TITLE
No command line help for ecagent_windows_sys.exe for the .yml file 

### ISSUE THREAD

**Issue by awaisbajwaml** [Enterprise-connect/ec-x-sdk#99] opened 2020-05-15 21:28 UTC
I was given the following two files [](url)

client-config1.yml
ecagent_windows_sys.exe

Contents of client-config1.yml file are below.

ec-config: conf: mod: client aid: VQkG10 tid: wRjT3X grp: local-aws-msk cid: corporate-sandbox-ec-preprod-client csc: ```<csc>``` dur: 3000 oat lpt: "7999" hca: "7000" dbg: true pxy: 

when I run the below on windows shell:

>> ecagent_windows_sys.exe

I get an error

EC_Error

Main packae exception unknown agent mode.

I think there should be some be some command line parameters telling the user to specify the YAML config file. Without this help the user is helpless and dependent of the customer support engineer and there is no documentation on this wiki for this.

**Comment by ayasuda2OO3** [comment] 2020-05-15 21:44
Thanks for the contribution, @awaisbajwaml 

It seems the yaml file might have been mal-formatted. Often time we ran across a ```tab``` vs ```double spaces``` that had led us to many troubles whilst launching agent. Please verify again.

fyi hashed out the ```csc``` part in the content as this tracker is public-facing.

**Comment by ramaraosrikakulapu** [comment] 2020-05-15 22:04
@awaisbajwaml Can you please confirm you were using the command ```ecagent_windows_sys.exe -cfg client-config1.yml```

**Comment by awaisbajwaml** [comment] 2020-05-16 05:43
@ramaraosrikakulapu 

Sorry for the confusion. 

Actually I didn't use any -cfg parameter. 

And here is the problem, the program should prompt the user and provide help about the command line parameters that it did not.

When I executed >>>ecagent_windows_sys.exe on the windows shell. It should prompt for the required -cfg parameter. That was missing.

Later I was told by the support person to use the -cfg arguments. 

So instead of support engineer the software should prompt the user if the required command line argument is missing. I hope I clarified,

**Comment by ayasuda2OO3** [comment] 2020-05-18 15:24
@awaisbajwaml thanks for the suggestion. it seems the issue is resolved with the suggested flag ```-cfg```? We will review it and make improvements to the ux if necessary. Meanwhile, we will leave this issue open for next three days in case any further questions.

**Closed as completed** 2020-05-23 16:08 UTC
Labels: question
